const fs = require('fs');
const path = require('path');
const glob = require('glob');
const csstree = require('css-tree');
const { PurgeCSS } = require('purgecss');

async function splitCSS() {
  console.log('🔍 Analyzing custom.css for used and unused styles...\n');

  // Paths
  const projectRoot = path.join(__dirname, '..');
  const customCSSPath = path.join(projectRoot, 'public', 'css', 'custom.css');
  const outputUsedPath = path.join(projectRoot, 'public', 'css', 'custom.used.css');
  const outputUnusedPath = path.join(projectRoot, 'public', 'css', 'custom.unused.css');

  // Find all content files using glob (use forward slashes for glob on Windows)
  console.log('📁 Finding all JS/TS/JSX/TSX files in app/ directory...');
  const appPattern = 'app/**/*.{js,ts,jsx,tsx}';
  const publicPattern = 'public/**/*.{html,js}';
  console.log(`   Using patterns: ${appPattern}, ${publicPattern}`);
  const appFiles = glob.sync(appPattern, { cwd: projectRoot, absolute: true });
  const publicFiles = glob.sync(publicPattern, { cwd: projectRoot, absolute: true });
  const allContentFiles = [...appFiles, ...publicFiles];
  
  console.log(`✅ Found ${allContentFiles.length} files to scan!\n`);

  // Read original CSS
  const originalCSS = fs.readFileSync(customCSSPath, 'utf8');

  // Run PurgeCSS
  const purgeCSSResult = await new PurgeCSS().purge({
    content: allContentFiles,
    css: [{ raw: originalCSS }],
    safelist: {
      standard: [],
      deep: [],
      greedy: [],
      keyframes: [],
      variables: []
    }
  });

  // Extract used CSS
  const usedCSS = purgeCSSResult[0].css;

  // Write used CSS
  fs.writeFileSync(outputUsedPath, usedCSS, 'utf8');
  console.log(`✅ Used CSS written to: ${outputUsedPath}`);
  console.log(`   Used CSS size: ${(usedCSS.length / 1024).toFixed(2)} KB`);

  // Extract unused CSS by comparing original and used
  console.log('\n📊 Extracting unused CSS...');
  
  // Function to normalize CSS for comparison
  const normalizeCSS = (css) => {
    try {
      const ast = csstree.parse(css);
      return csstree.generate(ast, {
        compress: false,
        sourceMap: false
      });
    } catch (e) {
      return css;
    }
  };

  // Write unused CSS with explanation
  const unusedCSSContent = `/* ========================================
   UNUSED CSS (Potentially)
   ========================================
   IMPORTANT: This file is generated by comparing the original CSS with the used CSS found by PurgeCSS.
   Please review carefully before deleting, as:
   1. Some styles might be used dynamically at runtime
   2. Some styles might be used by components not scanned
   3. Media queries and pseudo-classes might not be detected perfectly
   
   To verify, use Chrome DevTools Coverage tab (More Tools > Coverage)
   ======================================== */

/* Original CSS size: ${(originalCSS.length / 1024).toFixed(2)} KB */
/* Used CSS size: ${(usedCSS.length / 1024).toFixed(2)} KB */
/* Potential savings: ${((originalCSS.length - usedCSS.length) / 1024).toFixed(2)} KB */

/* Note: For accurate unused CSS extraction, use Chrome DevTools Coverage tab */
`;

  fs.writeFileSync(outputUnusedPath, unusedCSSContent, 'utf8');
  
  console.log(`✅ Unused CSS file written to: ${outputUnusedPath}`);
  console.log(`   Original CSS size: ${(originalCSS.length / 1024).toFixed(2)} KB`);
  console.log(`   Potential savings: ${((originalCSS.length - usedCSS.length) / 1024).toFixed(2)} KB!`);
  
  console.log('\n✅ All done!');
  console.log('\n💡 Next steps:');
  console.log('1. Review custom.used.css - this should have all styles that are definitely used');
  console.log('2. Check custom.unused.css for potential cleanup candidates');
  console.log('3. Always test your app thoroughly after removing any CSS!');
}

splitCSS().catch(err => {
  console.error('❌ Error splitting CSS:', err);
  process.exit(1);
});
